spring:
  application:
    name: TC_Back

  datasource:
    url: jdbc:mysql://localhost:3306/mini_mes
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

file:
  upload-dir: C:/uploads/